name: CI-CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write   # 👈 VERY IMPORTANT FIX

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: npm install -g htmlhint
      - run: htmlhint index.html

  cd:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
